"$schema" = 'https://starship.rs/config-schema.json'


format = """
$os\
$shell\
$username\
$directory\
$git_branch\
$git_status\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
$docker_context\
$fill\
$time\
$line_break$character"""

[os]
disabled = false
style = "bg:black fg:cyan"

[os.symbols]
Windows = " 󰍲"
Ubuntu = " 󰕈"
SUSE = " "
Raspbian = " 󰐿"
Mint = " 󰣭"
Macos = " "
Manjaro = " "
Linux = " 󰌽"
Gentoo = " 󰣨"
Fedora = " 󰣛"
Alpine = " "
Amazon = " "
Android = " "
Arch = " 󰣇"
Artix = " 󰣇"
CentOS = " "
Debian = " 󰣚"
Redhat = " 󱄛"
RedHatEnterprise = "󱄛"

[shell]
disabled = false
style = "bg:black fg:cyan"
format = "[ $indicator ]($style)"
[username]
show_always = true
style_user = "bg:black fg:white"
style_root = "bg:black fg:white"
format = '[ $user ]($style)'

[directory]
style = "fg:yellow bg:bright_black"
format = "[ $path ]($style)"
truncation_length = 5
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "fg:cyan bg:bright_black"
format = "[ ($symbol $branch) ]($style)"

[git_status]
style = "fg:cyan bg:bright_black"
format = "[($all_status$ahead_behind)]($style)"

[nodejs]
symbol = ""
style = "bg:cyan"
format = '[[ $symbol( $version) ](fg:black bg:cyan)]($style)'

[c]
symbol = " "
style = "bg:cyan"
format = '[[ $symbol( $version) ](fg:black bg:cyan)]($style)'

[rust]
symbol = ""
style = "bg:cyan"
format = '[[ $symbol( $version) ](fg:black bg:cyan)]($style)'

[golang]
symbol = ""
style = "bg:cyan"
format = '[[ $symbol( $version) ](fg:black bg:cyan)]($style)'

[php]
symbol = ""
style = "bg:cyan"
format = '[[ $symbol( $version) ](fg:black bg:cyan)]($style)'

[java]
symbol = " "
style = "bg:cyan"
format = '[[ $symbol( $version) ](fg:black bg:cyan)]($style)'

[kotlin]
symbol = ""
style = "bg:cyan"
format = '[[ $symbol( $version) ](fg:black bg:cyan)]($style)'

[haskell]
symbol = ""
style = "bg:cyan"
format = '[[ $symbol( $version) ](fg:black bg:cyan)]($style)'

[python]
symbol = ""
style = "bg:cyan"
format = '[[ $symbol( $version) ](fg:black bg:cyan)]($style)'

[docker_context]
symbol = ""
style = "bg:bright_black"
format = '[[ $symbol( $context) ](fg:cyan bg:black)]($style)'

[time]
disabled = false
time_format = "%I:%M %p"
style = "bg:yellow"
format = '[[  $time ](fg:black)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:green)'
error_symbol = '[](bold fg:red)'
vimcmd_symbol = '[](bold fg:green)'
vimcmd_replace_one_symbol = '[](bold fg:magenta)'
vimcmd_replace_symbol = '[](bold fg:magenta)'
vimcmd_visual_symbol = '[](bold fg:bright_magenta)'

[fill]
disabled = true
symbol = " "
